# Generated by Django 6.0.3 on 2026-03-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='Data and time of review creation'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_edited',
            field=models.DateTimeField(help_text='Data and time of review editing', null=True),
        ),
    ]
